# Generated by Django 3.2 on 2021-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlpost',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crawlpostsnapshot',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrecord',
            name='from_source',
            field=models.IntegerField(blank=True, choices=[(3, 'lambda Profile'), (0, 'Request'), (5, 'Lambda Request'), (4, 'Lambda Tag'), (2, 'Lambda'), (1, 'External Post API')], default=0),
        ),
    ]
