# Generated by Django 3.2 on 2021-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaohongshu_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiacrawlrecord',
            name='from_source',
            field=models.IntegerField(blank=True, choices=[(1, 'Featuring Request'), (2, 'Other API'), (0, 'Featuring Lambda')], default=0),
        ),
    ]
